import * as React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import theme from '../components/theme';
import Footer from '../components/Footer';


import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Menu from '@mui/material/Menu';
import MenuItem from '@mui/material/MenuItem';
import Typography from '@mui/material/Typography';

import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import CardHeader from '@mui/material/CardHeader';
import CardMedia from '@mui/material/CardMedia';

import Button from '@mui/material/Button';

import Grid from '@mui/material/Grid';
import Paper from '@mui/material/Paper';
import Alert from '@mui/material/Alert';
import AlertTitle from '@mui/material/AlertTitle';

import { ThemeProvider } from '@mui/material/styles';

export default function Home() {

  const [open, setOpen] = React.useState(false);

  const handleClick = () => {
    setOpen((prev) => !prev);
  };

  const handleClickAway = () => {
    setOpen(false);
  };

  const megamenu_styles = {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    zIndex: 1,
    borderBottom: '1px solid',
    p: 3,
    bgcolor: 'background.paper',
  };

  const main_menu_styles = {
    textTransform: 'uppercase',
    color: '#fff'
  };

  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeProvider theme={theme}>
        <Box sx={{bgcolor: 'brand.primary'}}>
          <Container>            
            <Grid container alignItems="flex-end">
              <Grid item xs={3}>
                  <img
                  src='/img/logo.svg'
                  alt="Picture of the author"
                  width={200}
                  style={{marginTop: "20px",marginBottom: "20px"}}
                  />
              </Grid>
              <Grid item xs={9}>
                  <Box sx={{ display: 'flex', alignItems: 'center', textAlign: 'center' }}>
                    <Typography sx={main_menu_styles}><a href onClick={handleClick}>Study</a></Typography>
                    <Typography sx={{ minWidth: 100 }}>Research</Typography>
                  </Box> 
              </Grid>
            </Grid>
          </Container>
        </Box>

        <Box sx={{ position: 'relative' }}>          
          {open ? (
            <Box sx={megamenu_styles}>
              Click me, I will stay visible until you click outside.
            </Box>
          ) : null}
        </Box>

        <div style={{background:"url(/img/banner.jpg)",height:"400px",backgroundPosition: "center",backgroundSize:"cover"}}></div>

        <Container>         

        <Alert severity="warning" sx={{my:2}}>
          <AlertTitle>Coronavirus (COVID-19)</AlertTitle>
          <a href="https://www.qub.ac.uk/home/coronavirus-faqs">COVID-19 FAQs</a>&nbsp;|&nbsp;<a href="https://www.qub.ac.uk/home/coronavirus-faqs/asymptomatic-testing">Asymptomatic Testing</a> | <a class="link" href="https://forms.office.com/Pages/ResponsePage.aspx?id=6ner6qW040mh6NbdI6HyhttEmBrbsE9JlZQYslaBsRRUNDhPVFcxVTZGR1dKQ1BYVUowU1RRUzgwVCQlQCN0PWcu">Self-Reporting Portal</a> |&nbsp;<a class="link" href="https://www.qub.ac.uk/sites/my-queens/working-together/get-ready/">Teaching Arrangements, Arrival and Vaccination</a>
        </Alert>


        <Grid container spacing={2}>
          <Grid item xs={12} md={4}>
              <Card sx={{p:3,bgcolor:'grey.light',boxShadow:0}}>                
                <CardMedia
                  component="img"
                  image="/img/bright-minds.png"
                  sx={{mb:2}}
                />
                <Typography variant="subtitle1" sx={{color:'brand.primary'}}>Welcome to Queen's: New Students</Typography>
                <Typography>Helping you get settled at Queen's - find out everything you need to know!</Typography>
              </Card> 
          </Grid>
          <Grid item xs={12} md={4}>
              <Card sx={{p:3,bgcolor:'grey.light',boxShadow:0}}>                
                <CardMedia
                  component="img"
                  image="/img/ug-open-days.jpg"
                  sx={{mb:2}}
                />
                <Typography variant="subtitle1" sx={{color:'brand.primary'}}>Welcome to Queen's: New Students</Typography>
                <Typography>Helping you get settled at Queen's - find out everything you need to know!</Typography>
              </Card> 
          </Grid>
          <Grid item xs={12} md={4}>
              <Card sx={{p:3,bgcolor:'grey.light',boxShadow:0}}>                
                <CardMedia
                  component="img"
                  image="/img/upskill-your-future.png"
                  sx={{mb:2}}
                />
                <Typography variant="subtitle1" sx={{color:'brand.primary'}}>Welcome to Queen's: New Students</Typography>
                <Typography>Helping you get settled at Queen's - find out everything you need to know!</Typography>
              </Card> 
          </Grid>
        </Grid>

        </Container>

        <Footer />

    </ThemeProvider>
    </>
  )
}
